swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: >
    Contains all available API endpoints in this codebase. This API allows users to sign up, log in, and manage their financial transactions. Users can create, retrieve, update, and delete transactions, as well as fetch transactions for the current month. All transaction endpoints require authentication via a bearer token and the userId to ensure that only the active user's transactions are accessed.
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/{userId}/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Create Transaction
      description: API for creating a new transaction for the specified user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of the user
          required: true
          type: string
        - in: body
          name: body
          description: Transaction object that needs to be created
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction created successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: List Transactions
      description: API for fetching a list of transactions for the specified user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of the user
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionListResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /user/{userId}/transaction/month:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get Transactions for Current Month
      description: API for fetching all transactions for the current month for the specified user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of the user
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionListResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /user/{userId}/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction Details
      description: API for fetching transaction details for the specified user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of the user
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction
      description: API for updating a transaction for the specified user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of the user
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Fields to update in the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete Transaction
      description: API for deleting a transaction for the specified user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          description: ID of the user
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
        description: HTTP status code
      message:
        type: string
        description: Response message
  LoginResponse:
    type: object
    properties:
      token:
        type: string
        description: JWT token
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserProfileResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          firstName:
            type: string
          lastName:
            type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      transactionName:
        type: string
        description: Name of the transaction
      transactionAmount:
        type: number
        format: double
        description: Amount of the transaction
      transactionType:
        type: string
        description: Type of the transaction
  TransactionUpdate:
    type: object
    properties:
      transactionName:
        type: string
        description: Name of the transaction
      transactionAmount:
        type: number
        format: double
        description: Amount of the transaction
      transactionType:
        type: string
        description: Type of the transaction
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
        description: HTTP status code
      message:
        type: string
        description: Response message
      body:
        $ref: '#/definitions/Transaction'
  TransactionListResponse:
    type: object
    properties:
      status:
        type: integer
        description: HTTP status code
      message:
        type: string
        description: Response message
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'